### ISSUE TITLE
Bottles: License Registration Error

### ISSUE THREAD

**Issue by richioniz0r** [balsamiq/balsamiq-wireframes-linux#13]
When registering the application via registration key, Balsamiq throws an error:

`[2022-11-21 08:55:48.069Z][Native] License Registration error
[2022-11-21 08:55:48.069Z][Native] Exception message: Unsupported PEM format...
[2022-11-21 08:55:48.108Z][Native] Exception stack:    at BalsamiqWireframes.Services.CryptoService.PemToXml(String pem) in D:\a\bwwindows\bwwindows\Balsamiq Wireframes\Services\CryptoService.cs:line 91
   at BalsamiqWireframes.Services.CryptoService.GetRSAFromFileUri(Uri uri) in D:\a\bwwindows\bwwindows\Balsamiq Wireframes\Services\CryptoService.cs:line 74
   at BalsamiqWireframes.Services.CryptoService.VerifySignature(String license, String signedHash) in D:\a\bwwindows\bwwindows\Balsamiq Wireframes\Services\CryptoService.cs:line 24
   at BalsamiqWireframesCommon.Utils.LicenseData.CheckLicense(ICryptoService cryptoService, IHardwareService hardwareService, ILogServiceManager logServiceManager) in D:\a\bwwindows\bwwindows\BalsamiqWireframesCommon\Utils\LicenseData.cs:line 64
   at BalsamiqWireframesCommon.Services.LocalFilesRegistration.checkLicense(RawLicenseData license, ICryptoService criptoService) in D:\a\bwwindows\bwwindows\BalsamiqWireframesCommon\Services\LocalFilesRegistration.cs:line 156
   at BalsamiqWireframesCommon.Services.LocalFilesRegistration.registerLicense(RawLicenseData license) in D:\a\bwwindows\bwwindows\BalsamiqWireframesCommon\Services\LocalFilesRegistration.cs:line 164
[2022-11-21 08:55:48.109Z][Native] License file not found`

Steps to reproduce:
* OS: Fedora 37
* Create a new bottle with caffe-7.20 / 64bit
* Install Balsamiq_Wireframes_4.6.3_x64_Setup.exe for all users
* Launch Balsamiq
* Open registration dialog, enter valid license key
* Balsamiq indicates that the license is valid (green checkmark)
* Click on "Register"
* Balsamiq shows an error message

Perhaps related to https://github.com/balsamiq/balsamiq-wireframes-linux/issues/12

**Comment by balsamiqGozzi** [comment]
please try with caffe-7.2 as said in the readme

**Comment by richioniz0r** [comment]
Thank you, caffe-7.2 works, as well as sys-wine-7.0
